services:
  postgresPresenca:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: QrCode-gen
    networks:
      qrcode_gen:

networks:
  qrcode_gen:
    driver: bridge
